FROM python:3.11-slim-bookworm

WORKDIR /usr/src/app
COPY requirements.txt .
COPY main.py .
COPY website/ ./website/
RUN pip install -r requirements.txt

# Install custom public package
RUN pip install "git+https://github.com/AnhNguyen20695/sit727-project-common.git"

EXPOSE 5000
ENTRYPOINT ["python3", "main.py", "-env", "dev"]