apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: gateway:latest
        name: gateway
        resources: {}
        imagePullPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ticket-microservice
  name: ticket-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-microservice
  template:
    metadata:
      labels:
        app: ticket-microservice
    spec:
      containers:
      - image: ticket-microservice:latest
        name: ticket-microservice
        resources: {}
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-microservice
spec:
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    app: ticket-microservice
  type: NodePort